# Generated by Django 3.1.12 on 2021-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_live_interface", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
