# Generated by Django 3.2.4 on 2021-06-02 21:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('channel_name', models.CharField(help_text='Channel name', max_length=255)),
                ('last_update_at', models.DateTimeField(blank=True, help_text='Date and time of the last update for this channel/page', null=True)),
                ('posts', wagtail.core.fields.StreamField([('post', wagtail.core.blocks.StructBlock([('message_id', wagtail.core.blocks.CharBlock(help_text='The message ID as supplied by the messaging app', required=False)), ('created', wagtail.core.blocks.DateTimeBlock(help_text='Date and time of message creation', required=False)), ('modified', wagtail.core.blocks.DateTimeBlock(help_text='Date and time of last update', required=False)), ('show', wagtail.core.blocks.BooleanBlock(default=True, help_text='Indicates if this message is shown/hidden', required=False)), ('content', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())]))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
