# Generated by Django 3.2.4 on 2021-06-03 21:26

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveblogpage',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='liveblogpage',
            name='last_update_at',
        ),
        migrations.AddField(
            model_name='liveblogpage',
            name='channel',
            field=models.CharField(default=1, help_text='The channel name', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveblogpage',
            name='posts',
            field=wagtail.core.fields.StreamField([('post', wagtail.core.blocks.StructBlock([('message_id', wagtail.core.blocks.CharBlock(help_text='The message ID as supplied by the messaging app', required=False)), ('created', wagtail.core.blocks.DateTimeBlock(help_text='Date and time of message creation', required=False)), ('modified', wagtail.core.blocks.DateTimeBlock(help_text='Date and time of last update', required=False)), ('show', wagtail.core.blocks.BooleanBlock(default=True, help_text='Indicates if this message is shown/hidden', required=False)), ('content', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock(form_classname='full title')), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())]))]))], blank=True),
        ),
    ]
