# Generated by Django 3.2.4 on 2021-06-05 13:48

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210603_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveblogpage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='liveblogpage',
            name='posts',
        ),
        migrations.AddField(
            model_name='liveblogpage',
            name='channel_name',
            field=models.CharField(default=1, help_text='Channel name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liveblogpage',
            name='last_update_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of the last update for this channel/page', null=True),
        ),
        migrations.AddField(
            model_name='liveblogpage',
            name='live_posts',
            field=wagtail.core.fields.StreamField([('live_post', wagtail.core.blocks.StructBlock([('message_id', wagtail.core.blocks.CharBlock(help_text="Message's ID")), ('created', wagtail.core.blocks.DateTimeBlock(help_text='Date and time of message creation')), ('modified', wagtail.core.blocks.DateTimeBlock(blank=True, help_text='Date and time of last update', required=False)), ('show', wagtail.core.blocks.BooleanBlock(help_text='Indicates if this message is shown/hidden', required=False)), ('content', wagtail.core.blocks.StreamBlock([('message', wagtail.core.blocks.TextBlock(help_text='Text of the message')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image of the message')), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='URL of the embed message'))]))]))], blank=True),
        ),
    ]
