# Generated by Django 3.2.4 on 2021-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="channel_id",
            field=models.CharField(blank=True, help_text="Channel ID", max_length=255),
        ),
    ]
