# Generated by Django 3.2 on 2021-07-09 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0005_alter_blogpage_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="last_updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Last update of this page",
            ),
        ),
    ]
