name: Wagtail Live CI

on:
  push:
    branches:
      - main
      - master
      - 'stable/**'

  pull_request:

jobs:
  test-sqlite:
    name: ${{ matrix.toxenv }}-sqlite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toxenv: 'python3.8-django2.2-wagtail2.12'
            python: 3.8
          - toxenv: 'python3.9-django3.2-wagtail2.13'
            python: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}

  lint:
    name: Lint ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]
        toxenv: ["black", "isort", "flake8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Run ${{ matrix.toxenv }}
        run: |
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}