name: Wagtail Live CI

on:
  push:
    branches:
      - main
      - master
      - 'stable/**'

  pull_request:

jobs:
  test-sqlite:
    name: ${{ matrix.toxenv }}-sqlite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Wagtail 2.12
          - toxenv: 'python3.7-django2.2-wagtail2.12'
            python: 3.7
          - toxenv: 'python3.8-django2.2-wagtail2.12'
            python: 3.8
          # Wagtail 2.14
          - toxenv: 'python3.7-django3.2-wagtail2.14'
            python: 3.7
          - toxenv: 'python3.8-django3.2-wagtail2.14'
            python: 3.8
          - toxenv: 'python3.9-django3.2-wagtail2.14'
            python: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -e '.[test]'
      - name: Test
        run: |
          pytest --cov wagtail_live
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  lint:
    name: Lint ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]
        toxenv: ["black", "isort", "flake8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Run ${{ matrix.toxenv }}
        run: |
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}